######################################################################
# Automatically generated by qmake (2.01a) ?? 31. ??? 00:08:28 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h myparam.h Percol2D.h plotter.h
SOURCES += main.cpp MainWindow.cpp myparam.cpp Percol2D.cpp plotter.cpp
