######################################################################
# Automatically generated by qmake (2.01a) ?? 6. ??? 23:20:41 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h percol2d.h
SOURCES += main.cpp mainwindow.cpp percol2d.cpp
include(mpi_percol.pri)