#!/bin/bash
#PBS -q g6_q
##PBS -l nodes=2:ppn=1,cput=00:10:00,walltime=15:00
##PBS -l nodes=2:ppn=1,cput=00:860:00,walltime=870:00
#PBS -l nodes=2:ppn=8,cput=00:100:00,walltime=135:00
##PBS -l nodes=4:ppn=1,cput=00:20:00,walltime=25:00
#PBS -k oe -j oe
#PBS -N Percolation
date
uname -a
cd $PBS_O_WORKDIR
pwd
mpirun -r ssh -genv I_MPI_DEVICE rdssm -n 16  ./mpi_percol
#mpirun  -n 2  ./mpi_percol
#mpirun -n 2  ./mpi_percol
#/home/ifs/otkach/IMPI/cpiicc 
date 
   
